postgresql:
  enabled: false
ccd:
  enabled: false

global:
  devMode: true
  idamApiUrl: ""
  s2sAuthUrl: ""
  cmcFrontendUrl: ""
  pdfServiceUrl: ""
  paymentUrl: ""
  feesUrl: ""
  sendLetterUrl: ""
  documentManagementUrl: ""
  dgAssemblyUrl: ""
  ccdCaseDataApiUrl: ""
  postgresqlHost: ""

java:
  image: hmctspublic.azurecr.io/cmc/claim-store:latest
  applicationPort: 4400
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
        - AppInsightsInstrumentationKey
        - citizen-oauth-client-secret
        - claim-store-s2s-secret
        - anonymous-caseworker-username
        - anonymous-caseworker-password
        - system-update-username
        - system-update-password
        - notify-api-key
        - milo-recipient
  environment:
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: claim-store
    REFORM_ENVIRONMENT: preview
    SPRING_MAIL_HOST: mta.reform.hmcts.net
    SPRING_MAIL_PORT: 25
    SPRING_MAIL_TEST_CONNECTION: false
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mta.reform.hmcts.net
    CLAIM_STORE_TEST_SUPPORT_ENABLED: true
    CMC_DB_USERNAME: hmcts
    CMC_DB_PASSWORD: hmcts
    CMC_DB_NAME: cmc
    CMC_DB_PORT: 5432
    CLAIM_STORE_DB_USERNAME: hmcts
    CLAIM_STORE_DB_PASSWORD: hmcts
    CLAIM_STORE_DB_NAME: claimstore
    CLAIM_STORE_DB_PORT: 5432
    FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
    FEATURE_TOGGLES_DIRECTIONS_QUESTIONNAIRE_ENABLED: true
    STAFF_NOTIFICATIONS_RECIPIENT: civilmoneyclaims+staff-int-tests@gmail.com
    LIVE_SUPPORT_RECIPIENT: civilmoneyclaims+live-support-int-tests@gmail.com
    LIVE_SUPPORT_SENDER: noreply@reform.hmcts.net
    STAFF_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    RPA_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    RPA_NOTIFICATIONS_SEALEDCLAIMRECIPIENT: civilmoneyclaims+rpa-claim-issued@gmail.com
    RPA_NOTIFICATIONS_MORETIMEREQUESTEDRECIPIENT: civilmoneyclaims+rpa-more-time-requested@gmail.com
    RPA_NOTIFICATIONS_RESPONSERECIPIENT: civilmoneyclaims+rpa-defence-response@gmail.com
    RPA_NOTIFICATIONS_COUNTYCOURTJUDGEMENTRECIPIENT: civilmoneyclaims+rpa-county-court-judgement@gmail.com
    RPA_NOTIFICATIONS_PAIDINFULLRECIPIENT: civilmoneyclaims+rpa-paid-in-full@gmail.com
    DOCUMENT_MANAGEMENT_USERROLES: caseworker-cmc,citizen
    MILO_CSV_SCHEDULE: '-'
    MILO_CSV_SENDER: noreply@reform.hmcts.net
    CLAIM_STAYED_SCHEDULE: ''
    FRONTEND_BASE_URL: '{{ .Values.global.cmcFrontendUrl }}'
    RESPOND_TO_CLAIM_URL: https://{{ tpl .Values.global.cmcFrontendUrl $}}/first-contact/start
    CORE_CASE_DATA_API_URL: '{{ .Values.global.ccdCaseDataApiUrl }}'
    IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
    IDAM_S2S_AUTH_URL: '{{ .Values.global.s2sAuthUrl }}'
    PDF_SERVICE_URL: '{{ .Values.global.pdfServiceUrl }}'
    SEND_LETTER_URL: '{{ .Values.global.sendLetterUrl }}'
    DOCUMENT_MANAGEMENT_URL: '{{ .Values.global.documentManagementUrl }}'
    DOC_ASSEMBLY_URL: '{{ .Values.global.dgAssemblyUrl }}'
    PAY_URL: '{{ .Values.global.paymentUrl }}'
    FEES_URL: '{{ .Values.global.feesUrl }}'
