
global:
  devMode: true
  subscriptionId: 1c4f0704-a29e-403d-b719-b90c34ef14c9
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  environment: aat
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  s2sAuthUrl: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  cmcFrontendUrl: "https://cmc-citizen-frontend-aat.service.core-compute-aat.internal"
  pdfServiceUrl: "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
  paymentUrl: "http://payment-api-aat.service.core-compute-aat.internal"
  feesUrl: "http://fees-register-api-aat.service.core-compute-aat.internal"
  sendLetterUrl: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
  documentManagementUrl: "http://dm-store-aat.service.core-compute-aat.internal"
  dgAssemblyUrl: "http://dg-docassembly-aat.service.core-compute-aat.internal"
  ccdCaseDataApiUrl: ""
  postgresqlHost: ""

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  nameOverride: postgres
  persistence:
    enabled: false

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  livenessFailureThreshold: 6
  livenessDelay: 75
  readinessDelay: 75
  environment:
    LOG_LEVEL: DEBUG
    CMC_DB_HOST: ${SERVICE_NAME}-postgres
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-data-store-api

ccd:
  enabled: true
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  postgresql:
    nameOverride: postgres
  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      CCD Admin:
        - https://admin-web-${SERVICE_FQDN}/oauth2redirect
  apiGateway:
    s2sKey: ${API_GATEWAY_S2S_KEY}
    idamClientSecret:
      value: ${API_GATEWAY_IDAM_SECRET}
  userProfileApi:
    authorisedServices: ccd_admin,ccd_data,ccd_definition,cmc_claim_store
  dataStoreApi:
    s2sKey: ${DATA_STORE_S2S_KEY}
    s2sAuthorisedServices: cmc_claim_store,ccd_gw
  definitionStoreApi:
    s2sKey: ${DEFINITION_STORE_S2S_KEY}
    s2sAuthorisedServices: ccd_admin,ccd_data,cmc_claim_store,ccd_gw
  caseManagementWeb:
    enabled: true
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  adminWeb:
    enabled: true
    s2sKey: ${ADMIN_S2S_KEY}
    idamClientSecret:
      value: ${ADMIN_WEB_IDAM_SECRET}
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - CMC
      users:
        - civilmoneyclaims+ccd@gmail.com|CMC|MoneyClaimCase|open
        - civilmoneyclaims+judge@gmail.com|CMC|MoneyClaimCase|orderForJudgeReview
        - civilmoneyclaims+la@gmail.com|CMC|MoneyClaimCase|readyForDirections
      userProfileDatabaseHost: ${SERVICE_NAME}-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile
    definition:
      enabled: true
      image: hmctspublic.azurecr.io/cmc/ccd-definition-importer:1.5.7
      environment:
        CCD_DEF_CLAIM_STORE_BASE_URL: http://${SERVICE_NAME}-java
      kvSecretRef: kvcreds
      gitSecretRef: kvcreds
      redirectUri: https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      definitionFilename: cmc-ccd.xlsx
      userRoles:
        - citizen
        - caseworker-cmc
        - caseworker-cmc-solicitor
        - caseworker-cmc-systemupdate
        - letter-holder
        - caseworker-autotest1
        - caseworker-cmc-anonymouscitizen
        - caseworker-cmc-judge
        - caseworker-cmc-legaladvisor
